targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: flutter_graphql_sample|lib/graphql/schema.graphql
          when_extensions:
            when: true
            maybeWhen: true
          # type_overrides:
          #   jsonb:
          #     name: JsonObject
          #     import: "package:built_value/json_object.dart"
          # custom_serializers:
          #   - import: "package:built_value/src/json_object_serializer.dart"
          #     name: JsonObjectSerializer
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: flutter_graphql_sample|lib/graphql/schema.graphql
